// Generated by CoffeeScript 1.9.3
(function() {
  var BrowserWindow, app, mainWindow, setup, spawn;

  spawn = require('child_process').spawn;

  setup = function(root) {};

  app = require('app');

  BrowserWindow = require('browser-window');

  require('crash-reporter').start();

  mainWindow = null;

  app.on('window-all-closed', function() {
    if (process.platform !== 'darwin') {
      app.quit();
    }
  });

  app.on('ready', function() {
    mainWindow = new BrowserWindow({
      width: 1152,
      height: 685
    });
    mainWindow.loadUrl('http://localhost:8080/dashboard/?user=Admin');
    mainWindow.on('closed', function() {
      mainWindow = null;
    });
  });

}).call(this);
